features=["driver_gps_accuracy","trip_distance", "driver_distance", "event_hour", "event_day","driver_historical_response_time","created_bookings","driver_historical_completed_bookings"]
target="is_accepted"
test_size=0.2

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false

[gradient_boosting]
n_estimators=300
max_depth=30
min_samples_leaf=12
random_state=33
